spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/nexus_db
    username: postgres
    password: ${DEV_DB_PASSWORD}  # Sourced securely from your untracked local .env
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}

app:
  base-url: "http://localhost:8080"
  mail-from: "no-reply@dev.nexus.local"
  jwt-secret: "dev_secure_environment_signing_key_must_be_long_and_robust_32_bytes_minimum"
  jwt-expiration-ms: 86400000 # 24 Hours
  allowed-origins:
    - "http://localhost:8080"
    - "http://127.0.0.1:5500" # Local Live Server extension testing port
    - "http://localhost:3000"


cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:8080